Fix various compilation problems for MSVC (#4403)
* Use INT32_MIN for -2147483648 and INT32_MAX for 2147483647

This fixes MSVC compilation error C4146: "unary minus operator
applied to unsigned type, result still unsigned" on WIN32.

On a 32bit int environment, 2147483648 is unsigned long so negating it
does not produce -2147483648 but results positive 2147483648UL.
INT32_MIN properly produces -2147483648 portably.

* Initialize a pointer variable with NULL

This fixes MSVC compilation error C4703: "potentially uninitialized
local pointer variable 'kind' used"

* Remove va_copy() workaround for MSVC

Recent versions of Visual Studio that can compile the Angband
source code (Visual Studio 2015 and later) supports va_copy()
so the workaround should not be used; it just works, not
guaranteed to work.